Rework doc build to not use shell script and Docker img

diff --git a/.github/workflows/docs.yaml b/.github/workflows/docs.yaml
--- a/.github/workflows/docs.yaml
+++ b/.github/workflows/docs.yaml
@@ -23,6 +23,9 @@ jobs:
   build-documentation:
     if: github.repository == 'apache/flink-kubernetes-operator'
     runs-on: ubuntu-latest
+    env:
+      HUGO_REPO: https://github.com/gohugoio/hugo/releases/download/v0.104.0/hugo_extended_0.104.0_Linux-64bit.tar.gz
+      HUGO_ARTIFACT: hugo_extended_0.104.0_Linux-64bit.tar.gz
     strategy:
       max-parallel: 1
       matrix:
@@ -31,7 +34,12 @@ jobs:
           - release-1.13
           - release-1.12
     steps:
-      - uses: actions/checkout@v3
+      - name: Set up Temurin JDK 17
+        uses: actions/setup-java@v4
+        with:
+          distribution: temurin
+          java-version: 17
+      - uses: actions/checkout@v4
         with:
           ref: ${{ matrix.branch }}
       - name: Set branch environment variable
@@ -49,7 +57,34 @@ jobs:
           fi
       - name: Build documentation
         run: |
-          docker run  --rm --volume "$PWD:/root/flink-kubernetes-operator" chesnay/flink-ci:java_8_11 bash -c "cd /root/flink-kubernetes-operator && ./.github/workflows/docs.sh"
+          if ! curl --fail -OL "$HUGO_REPO" ; then
+            echo "Failed to download Hugo binary"
+            exit 1
+          fi
+          tar -zxvf "$HUGO_ARTIFACT"
+          git submodule update --init --recursive
+
+          # generate docs into docs/target
+          ./hugo -v --source docs --destination target
+          if [ $? -ne 0 ]; then
+            echo "Error building the docs"
+            exit 1
+          fi
+
+          # build Java docs
+          mkdir -p docs/target/api
+      
+          mvn javadoc:aggregate -B \
+          -DadditionalJOption="-Xdoclint:none" \
+          -DadditionalJOption="--allow-script-in-comments" \
+          -DexcludePackageNames="org.apache.flink.examples" \
+          -Dmaven.javadoc.failOnError=false \
+          -Dcheckstyle.skip=true \
+          -Dspotless.check.skip=true \
+          -Denforcer.skip=true \
+          -Dheader="<a href=\"http://flink.apache.org/\" target=\"_top\"><h1>Back to Flink Website</h1></a> <script>var _paq=window._paq=window._paq||[];_paq.push([\"disableCookies\"]),_paq.push([\"setDomains\",[\"*.flink.apache.org\",\"*.nightlies.apache.org/flink\"]]),_paq.push([\"trackPageView\"]),_paq.push([\"enableLinkTracking\"]),function(){var u=\"//matomo.privacy.apache.org/\";_paq.push([\"setTrackerUrl\",u+\"matomo.php\"]),_paq.push([\"setSiteId\",\"1\"]);var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s)}();</script>"
+      
+          mv target/site/apidocs docs/target/api/java
       - name: Upload documentation
         uses: ./.github/actions/rsync-deployments
         with:
